# python file to generate the dataset.xml, walk.graphml and shuttle.graphml file

# dataset.xml generation
from xml.etree import ElementTree
from xml.etree.ElementTree import Element, SubElement
from xml.dom import minidom

# list of canteen names
canteen = ["Food Court 1",
           "Food Court 2",
           "Food Court 9",
           "Food Court 11",
           "Food Court 13",
           "Food Court 14",
           "Food Court 16",
           "Foodgle Food Court",
           "North Hill Food Court",
           "Pioneer Food Court",
           "North Spine Food Court",
           "Peach Garden Chinese Restaurant",
           "Pizza Hut Express",
           "Subway",
           "Koufu @ the South Spine"]

# list of the corresponding locations of the canteens in the canteen list
canteen_location = [(560, 558),
                    (608, 478),
                    (758, 327),
                    (888, 270),
                    (562, 189),
                    (652, 195),
                    (510, 244),
                    (830, 213),
                    (934, 377),
                    (634, 668),
                    (332, 335),
                    (353, 316),
                    (357, 318),
                    (354, 336),
                    (264, 586)]

# list of the rankings of the canteens
rankings = [2, 6, 1, 8, 11, 9, 13, 5, 15, 4, 10, 7, 3, 12, 14]

# list of the availability of halal foods
halals = [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1]

# list of the availability of vegetarian foods
vegs = [0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1]

# dictionary of stalls, with the names as the keys and signature food and price as the values
stalls = {"Noodle Stall": ("Mixed Bee Hoon", 3),
        "India Food": ("Aloo Mattar Paneer", 2),
        "Si Chuan Mei Shi": ("Spicy Fragrant Pot", 9),
        "Kiso Japanese Cuisine": ("DC - Chicken Katsu Don", 3),
        "Korean Cuisine": ("Tomatoes & Eggs", 4),
        "Thai Cuisine": ("Chicken Fried Noodles", 4.5)
         }

# dictionary of canteens, with the names as the keys and a list of the stalls in the canteen as the values
canteen_stall = {"Food Court 1": ["Noodle Stall", "Korean Cuisine", "Si Chuan Mei Shi"],
           "Food Court 2": ["India Food", "Korean Cuisine", "Kiso Japanese Cuisine"],
           "Food Court 9": ["India Food","Thai Cuisine","Kiso Japanese Cuisine"],
           "Food Court 11": ["India Food","Thai Cuisine","Kiso Japanese Cuisine"],
           "Food Court 13": ["Si Chuan Mei Shi","Thai Cuisine","Noodle Stall"],
           "Food Court 14": ["India Food","Korean Cuisine","Si Chuan Mei Shi"],
           "Food Court 16": ["India Food","Korean Cuisine","Noodle Stall"],
           "Foodgle Food Court": ["India Food","Si Chuan Mei Shi","Noodle Stall"],
           "North Hill Food Court": ["India Food","Korean Cuisine","Noodle Stall"],
           "Pioneer Food Court": ["India Food","Korean Cuisine","Thai Cuisine"],
           "North Spine Food Court": ["Si Chuan Mei Shi","Korean Cuisine","Thai Cuisine"],
           "Peach Garden Chinese Restaurant": ["Si Chuan Mei Shi","Korean Cuisine","Noodle Stall"],
           "Pizza Hut Express": ["Si Chuan Mei Shi","Korean Cuisine","Thai Cuisine"],
           "Subway": ["Si Chuan Mei Shi","Korean Cuisine","Thai Cuisine"],
           "Koufu @ the South Spine": ["Si Chuan Mei Shi","Korean Cuisine","Thai Cuisine"]}

# helper function to generate dataset.xml
def generate_xml():

    global ranking

    root = Element('graph')

    for i in range(len(canteen)):

        place = SubElement(root, 'canteen')
        name = SubElement(place, 'name')
        name.text = canteen[i]

        location_x = SubElement(place, 'location_x')
        location_x.text = str(canteen_location[i][0])

        location_y = SubElement(place, 'location_y')
        location_y.text = str(canteen_location[i][1])

        ranking = SubElement(place, 'ranking')
        ranking.text = str(rankings[i])

        halal = SubElement(place, 'halal')
        halal.text = str(halals[i])

        veg = SubElement(place, 'veg')
        veg.text = str(vegs[i])

        for j in range(len(canteen_stall[canteen[i]])):
            stall = SubElement(place, 'stall')
            stall.text = canteen_stall[canteen[i]][j]

            # signature = SubElement(stall, 'signature')
            # signature.text = stalls[canteen_stall[canteen[i]][j]][0]
            #
            # price = SubElement(stall, 'price')
            # price.text = str(stalls[canteen_stall[canteen[i]][j]][1])

    for key in stalls:
        place = SubElement(root, 'stall')
        name = SubElement(place, 'name')
        name.text = key

        signature = SubElement(place, 'signature')
        signature.text = stalls[key][0]

        price = SubElement(place, 'price')
        price.text = str(stalls[key][1])

    for i in range(len(mark)):

        place = SubElement(root, 'mark')
        name = SubElement(place, 'name')
        name.text = mark[i]

        location_x = SubElement(place, 'location_x')
        location_x.text = str(mark_location[i][0])

        location_y = SubElement(place, 'location_y')
        location_y.text = str(mark_location[i][1])

    output_file = open('dataset/dataset.xml', 'w')
    #output_file.write('<?xml version="1.0"?>')

    parsed = minidom.parseString(ElementTree.tostring(root, 'utf-8'))
    output_file.write(parsed.toprettyxml(indent="  "))

    output_file.close()


# walk.graphml and shuttle.graphml generation
import networkx as nx

# list of marks which serves as the reference points in the graph to facilitate breadth-first search
mark = ["Hall 16",
        "Hall 3",
        "Hall 12",
        "Hall 13",
        "Hall 14",
        "Hall 15",
        "New Hall",
        "North Hill Hall",
        "Hall 10",
        "Hall 9",
        "Hall 8",
        "Hall 11",
        "ADM",
        "Hall 2",
        "Hall 1",
        "Hall 6",
        "SRC",
        "C&P Hall",
        "Hall 5",
        "Hall 4",
        "CHC",
        "Hive",
        "SPMS",
        "Hall 7",
        "EEE1",
        "EEE2",
        "WKW",
        "Unknown",
        "Medi School",
        "SBS",
        "Nanyang Audi",
        "SS",
        "CEE",
        "Earth",
        "SCSE",
        "MAE",
        "NS",
        "NS Plaza"]

# list of the corresponding locations of the marks in the mark list
mark_location = [(520, 260),
                 (555, 260),
                 (520, 206),
                 (585, 200),
                 (645, 200),
                 (700, 190),
                 (820, 215),
                 (885, 225),
                 (820, 264),
                 (753, 320),
                 (685, 364),
                 (890, 273),
                 (593, 383),
                 (556, 457),
                 (572, 646),
                 (645, 567),
                 (719, 586),
                 (635, 688),
                 (521, 698),
                 (464, 646),
                 (376, 598),
                 (304, 567),
                 (228, 590),
                 (108, 589),
                 (209, 524),
                 (209, 479),
                 (154, 504),
                 (177, 452),
                 (189, 368),
                 (223, 389),
                 (240, 437),
                 (264, 352),
                 (258, 368),
                 (318, 337),
                 (374, 421),
                 (421, 402),
                 (350, 387),
                 (389, 348)]

# helper function to connect the marks on the graph by weighted edges, whose value represents the traveling time between two marks
def add_edges_to_shuttle(graph):
    graph.add_weighted_edges_from([("Hall 16", "Food Court 16", 0),
                                   ("Hall 16", "Hall 3", 1),
                                   ("Hall 16", "Hall 12", 2),
                                   ("Hall 16", "Hall 13", 3),
                                   ("Hall 16", "Hall 14", 5),
                                   ("Hall 16", "Hall 15", 8),
                                   ("Hall 16", "New Hall", 5),
                                   ("Hall 16", "North Hill Hall", 8),
                                   ("Hall 16", "Hall 10", 10),
                                   ("Hall 16", "Hall 9", 12),
                                   ("Hall 16", "Hall 8", 12),
                                   ("Hall 16", "Hall 11", 10),
                                   ("Hall 16", "ADM", 10),
                                   ("Hall 16", "Hall 2", 12),
                                   ("Hall 16", "Hall 1", 15),
                                   ("Hall 16", "Hall 6", 15),
                                   ("Hall 16", "SRC", 18),
                                   ("Hall 16", "C&P Hall", 18),
                                   ("Hall 16", "Hall 5", 20),
                                   ("Hall 16", "Hall 4", 22),
                                   ("Hall 16", "CHC", 20),
                                   ("Hall 16", "Hive", 15),
                                   ("Hall 16", "SPMS", 15),
                                   ("Hall 16", "Hall 7", 17),
                                   ("Hall 16", "EEE1", 12),
                                   ("Hall 16", "EEE2", 13),
                                   ("Hall 16", "WKW", 15),
                                   ("Hall 16", "Unknown", 10),
                                   ("Hall 16", "Medi School", 10),
                                   ("Hall 16", "SBS", 10),
                                   ("Hall 16", "Nanyang Audi", 10),
                                   ("Hall 16", "SS", 15),
                                   ("Hall 16", "CEE", 10),
                                   ("Hall 16", "Earth", 8),
                                   ("Hall 16", "SCSE", 10),
                                   ("Hall 16", "MAE", 8),
                                   ("Hall 16", "NS", 10),
                                   ("Hall 16", "NS Plaza", 8),
                                   # end of hall 16
                                   ("Hall 3", "Hall 12", 3),
                                   ("Hall 3", "Hall 13", 2),
                                   ("Hall 3", "Hall 14", 4),
                                   ("Hall 3", "Hall 15", 7),
                                   ("Hall 3", "New Hall", 5),
                                   ("Hall 3", "North Hill Hall", 8),
                                   ("Hall 3", "Hall 10", 10),
                                   ("Hall 3", "Hall 9", 12),
                                   ("Hall 3", "Hall 8", 12),
                                   ("Hall 3", "Hall 11", 10),
                                   ("Hall 3", "Hall 5", 20),
                                   ("Hall 3", "Hall 4", 22),
                                   ("Hall 3", "CHC", 20),
                                   ("Hall 3", "Hive", 15),
                                   ("Hall 3", "SPMS", 15),
                                   ("Hall 3", "Hall 7", 17),
                                   ("Hall 3", "EEE1", 12),
                                   ("Hall 3", "EEE2", 13),
                                   ("Hall 3", "WKW", 15),
                                   ("Hall 3", "Unknown", 10),
                                   ("Hall 3", "Medi School", 10),
                                   # end of hall 3
                                   ("Hall 12", "Hall 13", 1),
                                   ("Hall 12", "Hall 14", 4),
                                   ("Hall 12", "Hall 15", 7),
                                   ("Hall 12", "New Hall", 4),
                                   ("Hall 12", "North Hill Hall", 7),
                                   ("Hall 12", "Hall 10", 9),
                                   ("Hall 12", "Hall 9", 11),
                                   ("Hall 12", "Hall 8", 11),
                                   ("Hall 12", "Hall 11", 9),
                                   ("Hall 12", "C&P Hall", 16),
                                   ("Hall 12", "Hall 5", 18),
                                   ("Hall 12", "Hall 4", 20),
                                   ("Hall 12", "CHC", 18),
                                   ("Hall 12", "Hive", 13),
                                   ("Hall 12", "SPMS", 13),
                                   ("Hall 12", "Hall 7", 15),
                                   ("Hall 12", "EEE1", 10),
                                   ("Hall 12", "EEE2", 11),
                                   ("Hall 12", "WKW", 13),
                                   ("Hall 12", "Unknown", 8),
                                   ("Hall 12", "Medi School", 8),
                                   ("Hall 12", "SBS", 8),
                                   ("Hall 12", "Nanyang Audi", 8),
                                   # end of hall 12
                                   ("Hall 13", "Food Court 13", 0),
                                   ("Hall 13", "Hall 14", 3),
                                   ("Hall 13", "Hall 15", 6),
                                   ("Hall 13", "New Hall", 4),
                                   ("Hall 13", "North Hill Hall", 7),
                                   ("Hall 13", "Hall 10", 9),
                                   ("Hall 13", "Hall 9", 11),
                                   ("Hall 13", "Hall 8", 11),
                                   ("Hall 13", "Hall 11", 9),
                                   ("Hall 13", "C&P Hall", 16),
                                   ("Hall 13", "Hall 5", 18),
                                   ("Hall 13", "Hall 4", 20),
                                   ("Hall 13", "CHC", 18),
                                   ("Hall 13", "Hive", 13),
                                   ("Hall 13", "SPMS", 13),
                                   ("Hall 13", "Hall 7", 15),
                                   ("Hall 13", "EEE1", 10),
                                   ("Hall 13", "EEE2", 11),
                                   ("Hall 13", "WKW", 13),
                                   ("Hall 13", "Unknown", 8),
                                   ("Hall 13", "Medi School", 8),
                                   ("Hall 13", "SBS", 8),
                                   ("Hall 13", "Nanyang Audi", 8),
                                   # end of Hall 13
                                   ("Hall 14", "Food Court 14", 0),
                                   ("Hall 14", "Hall 15", 1),
                                   ("Hall 14", "New Hall", 5),
                                   ("Hall 14", "North Hill Hall", 8),
                                   ("Hall 14", "Hall 10", 7),
                                   ("Hall 14", "Hall 9", 9),
                                   ("Hall 14", "Hall 8", 9),
                                   ("Hall 14", "Hall 11", 7),
                                   ("Hall 14", "ADM", 10),
                                   ("Hall 14", "Hall 2", 12),
                                   ("Hall 14", "Hall 1", 15),
                                   ("Hall 14", "Hall 6", 15),
                                   ("Hall 14", "SRC", 18),
                                   ("Hall 14", "C&P Hall", 18),
                                   ("Hall 14", "Hall 5", 20),
                                   ("Hall 14", "Hall 4", 22),
                                   ("Hall 14", "CHC", 20),
                                   ("Hall 14", "Hive", 15),
                                   ("Hall 14", "SPMS", 15),
                                   ("Hall 14", "Hall 7", 17),
                                   ("Hall 14", "EEE1", 12),
                                   ("Hall 14", "EEE2", 13),
                                   ("Hall 14", "WKW", 15),
                                   ("Hall 14", "Unknown", 12),
                                   ("Hall 14", "Medi School", 12),
                                   ("Hall 14", "SBS", 12),
                                   ("Hall 14", "Nanyang Audi", 12),
                                   ("Hall 14", "SS", 15),
                                   ("Hall 14", "CEE", 10),
                                   ("Hall 14", "Earth", 8),
                                   ("Hall 14", "SCSE", 10),
                                   ("Hall 14", "MAE", 8),
                                   ("Hall 14", "NS", 10),
                                   ("Hall 14", "NS Plaza", 8),
                                   # end of Hall 14
                                   ("Hall 15", "New Hall", 3),
                                   ("Hall 15", "North Hill Hall", 5),
                                   # end of Hall 15
                                   ("New Hall", "Foodgle Food Court", 0),
                                   ("New Hall", "North Hill Hall", 5),
                                   ("New Hall", "Hall 10", 5),
                                   ("New Hall", "Hall 9", 6),
                                   ("New Hall", "Hall 8", 6),
                                   ("New Hall", "Hall 11", 5),
                                   ("New Hall", "ADM", 7),
                                   ("New Hall", "Hall 2", 9),
                                   ("New Hall", "Hall 1", 11),
                                   ("New Hall", "Hall 6", 11),
                                   ("New Hall", "SRC", 15),
                                   ("New Hall", "C&P Hall", 18),
                                   ("New Hall", "Hall 5", 20),
                                   ("New Hall", "Hall 4", 22),
                                   ("New Hall", "CHC", 20),
                                   ("New Hall", "Hive", 15),
                                   ("New Hall", "SPMS", 15),
                                   ("New Hall", "Hall 7", 17),
                                   ("New Hall", "EEE1", 17),
                                   ("New Hall", "EEE2", 18),
                                   ("New Hall", "WKW", 18),
                                   ("New Hall", "Unknown", 15),
                                   ("New Hall", "Medi School", 15),
                                   ("New Hall", "SBS", 15),
                                   ("New Hall", "Nanyang Audi", 15),
                                   ("New Hall", "SS", 17),
                                   ("New Hall", "CEE", 12),
                                   ("New Hall", "Earth", 12),
                                   ("New Hall", "SCSE", 14),
                                   ("New Hall", "MAE", 12),
                                   ("New Hall", "NS", 14),
                                   ("New Hall", "NS Plaza", 12),
                                   # end of New Hall
                                   ("North Hill Hall", "North Hill Food Cour", 0),
                                   ("North Hill Hall", "Hall 10", 1),
                                   ("North Hill Hall", "Hall 9", 2),
                                   ("North Hill Hall", "Hall 8", 2),
                                   ("North Hill Hall", "Hall 11", 1),
                                   ("North Hill Hall", "ADM", 5),
                                   ("North Hill Hall", "Hall 2", 7),
                                   ("North Hill Hall", "Hall 1", 9),
                                   ("North Hill Hall", "Hall 6", 9),
                                   ("North Hill Hall", "SRC", 12),
                                   ("North Hill Hall", "C&P Hall", 12),
                                   ("North Hill Hall", "Hall 5", 17),
                                   ("North Hill Hall", "Hall 4", 19),
                                   ("North Hill Hall", "CHC", 20),
                                   ("North Hill Hall", "Hive", 20),
                                   ("North Hill Hall", "SPMS", 22),
                                   ("North Hill Hall", "Hall 7", 25),
                                   ("North Hill Hall", "EEE1", 17),
                                   ("North Hill Hall", "EEE2", 17),
                                   ("North Hill Hall", "WKW", 19),
                                   ("North Hill Hall", "Unknown", 15),
                                   ("North Hill Hall", "Medi School", 15),
                                   ("North Hill Hall", "SBS", 15),
                                   ("North Hill Hall", "Nanyang Audi", 15),
                                   ("North Hill Hall", "SS", 17),
                                   ("North Hill Hall", "CEE", 12),
                                   ("North Hill Hall", "Earth", 10),
                                   ("North Hill Hall", "SCSE", 12),
                                   ("North Hill Hall", "MAE", 10),
                                   ("North Hill Hall", "NS", 12),
                                   ("North Hill Hall", "NS Plaza", 10),
                                   # end of North Hill Hall
                                   ("Hall 9", "Food Court 9", 0),
                                   ("Hall 9", "Hall 8", 1),
                                   ("Hall 9", "Hall 11", 2),
                                   ("Hall 9", "ADM", 5),
                                   ("Hall 9", "Hall 2", 5),
                                   ("Hall 9", "Hall 1", 7),
                                   ("Hall 9", "Hall 6", 7),
                                   ("Hall 9", "SRC", 9),
                                   ("Hall 9", "C&P Hall", 9),
                                   ("Hall 9", "Hall 5", 13),
                                   ("Hall 9", "Hall 4", 15),
                                   ("Hall 9", "CHC", 17),
                                   ("Hall 9", "Hive", 17),
                                   ("Hall 9", "SPMS", 20),
                                   ("Hall 9", "Hall 7", 22),
                                   ("Hall 9", "EEE1", 22),
                                   ("Hall 9", "EEE2", 22),
                                   ("Hall 9", "WKW", 22),
                                   ("Hall 9", "Unknown", 20),
                                   ("Hall 9", "Medi School", 20),
                                   ("Hall 9", "SBS", 20),
                                   ("Hall 9", "Nanyang Audi", 20),
                                   ("Hall 9", "SS", 22),
                                   ("Hall 9", "CEE", 17),
                                   ("Hall 9", "Earth", 17),
                                   ("Hall 9", "SCSE", 17),
                                   ("Hall 9", "MAE", 15),
                                   ("Hall 9", "NS", 17),
                                   ("Hall 9", "NS Plaza", 15),
                                   # end of Hall 9
                                   ("Hall 8", "ADM", 3),
                                   ("Hall 8", "Hall 2", 3),
                                   ("Hall 8", "Hall 1", 5),
                                   ("Hall 8", "Hall 6", 5),
                                   ("Hall 8", "SRC", 7),
                                   ("Hall 8", "C&P Hall", 7),
                                   # end of Hall 8
                                   ("ADM", "Hall 2", 2),
                                   ("ADM", "Hall 1", 3),
                                   ("ADM", "Hall 6", 3),
                                   ("ADM", "SRC", 5),
                                   ("ADM", "C&P Hall", 7),
                                   ("ADM", "Hall 5", 12),
                                   ("ADM", "Hall 4", 12),
                                   ("ADM", "CHC", 15),
                                   ("ADM", "Hive", 12),
                                   ("ADM", "SPMS", 12),
                                   ("ADM", "Hall 7", 15),
                                   ("ADM", "EEE1", 12),
                                   ("ADM", "EEE2", 13),
                                   ("ADM", "WKW", 15),
                                   ("ADM", "Unknown", 10),
                                   ("ADM", "Medi School", 10),
                                   ("ADM", "SBS", 10),
                                   ("ADM", "Nanyang Audi", 10),
                                   ("ADM", "SS", 15),
                                   ("ADM", "CEE", 10),
                                   ("ADM", "Earth", 8),
                                   ("ADM", "SCSE", 10),
                                   ("ADM", "MAE", 8),
                                   ("ADM", "NS", 10),
                                   ("ADM", "NS Plaza", 8),
                                   # end of ADM
                                   ("Hall 2", "Food Court 2", 0),
                                   ("Hall 2", "Hall 1", 2),
                                   ("Hall 2", "Hall 6", 2),
                                   ("Hall 2", "SRC", 3),
                                   ("Hall 2", "C&P Hall", 5),
                                   ("Hall 2", "Hall 5", 8),
                                   ("Hall 2", "Hall 4", 10),
                                   ("Hall 2", "CHC", 10),
                                   ("Hall 2", "Hive", 10),
                                   ("Hall 2", "SPMS", 15),
                                   ("Hall 2", "Hall 7", 17),
                                   ("Hall 2", "EEE1", 12),
                                   ("Hall 2", "EEE2", 13),
                                   ("Hall 2", "WKW", 15),
                                   ("Hall 2", "Unknown", 10),
                                   ("Hall 2", "Medi School", 10),
                                   ("Hall 2", "SBS", 10),
                                   ("Hall 2", "Nanyang Audi", 5),
                                   ("Hall 2", "SS", 5),
                                   ("Hall 2", "CEE", 5),
                                   ("Hall 2", "Earth", 8),
                                   ("Hall 2", "SCSE", 5),
                                   ("Hall 2", "MAE", 8),
                                   ("Hall 2", "NS", 5),
                                   ("Hall 2", "NS Plaza", 8),
                                   # end of hall 2
                                   ("Hall 1", "Food Court 1", 0),
                                   ("Hall 1", "Hall 6", 1),
                                   ("Hall 1", "SRC", 3),
                                   ("Hall 1", "C&P Hall", 1),
                                   ("Hall 1", "Hall 5", 3),
                                   ("Hall 1", "Hall 4", 8),
                                   ("Hall 1", "CHC", 10),
                                   ("Hall 1", "Hive", 10),
                                   ("Hall 1", "SPMS", 12),
                                   ("Hall 1", "Hall 7", 15),
                                   ("Hall 1", "EEE1", 12),
                                   ("Hall 1", "EEE2", 13),
                                   ("Hall 1", "WKW", 15),
                                   ("Hall 1", "Unknown", 10),
                                   ("Hall 1", "Medi School", 10),
                                   ("Hall 1", "SBS", 10),
                                   ("Hall 1", "Nanyang Audi", 10),
                                   ("Hall 1", "SS", 15),
                                   ("Hall 1", "CEE", 15),
                                   ("Hall 1", "Earth", 18),
                                   ("Hall 1", "SCSE", 15),
                                   ("Hall 1", "MAE", 18),
                                   ("Hall 1", "NS", 15),
                                   ("Hall 1", "NS Plaza", 18),
                                   # end of Hall 1
                                   ("Hall 6", "SRC", 1),
                                   ("Hall 6", "C&P Hall", 1),
                                   # end of Hall 6
                                   ("C&P Hall", "Pioneer Food Court", 0),
                                   # end of C&P Hall
                                   ("Hall 5", "Hall 4", 1),
                                   ("Hall 5", "CHC", 3),
                                   ("Hall 5", "Hive", 5),
                                   ("Hall 5", "SPMS", 5),
                                   ("Hall 5", "Hall 7", 7),
                                   ("Hall 5", "EEE1", 5),
                                   ("Hall 5", "EEE2", 5),
                                   ("Hall 5", "WKW", 7),
                                   ("Hall 5", "Unknown", 10),
                                   ("Hall 5", "Medi School", 10),
                                   ("Hall 5", "SBS", 10),
                                   ("Hall 5", "Nanyang Audi", 10),
                                   ("Hall 5", "SS", 15),
                                   ("Hall 5", "CEE", 10),
                                   ("Hall 5", "Earth", 8),
                                   ("Hall 5", "SCSE", 10),
                                   ("Hall 5", "MAE", 8),
                                   ("Hall 5", "NS", 10),
                                   ("Hall 5", "NS Plaza", 8),
                                   # end of Hall 5
                                   ("Hall 4", "CHC", 3),
                                   ("Hall 4", "Hive", 5),
                                   ("Hall 4", "SPMS", 5),
                                   ("Hall 4", "Hall 7", 7),
                                   ("Hall 4", "EEE1", 5),
                                   ("Hall 4", "EEE2", 5),
                                   # end of Hall 4
                                   ("CHC", "Hive", 1),
                                   ("CHC", "SPMS", 2),
                                   ("CHC", "Hall 7", 3),
                                   ("CHC", "EEE1", 3),
                                   ("CHC", "EEE2", 3),
                                   ("CHC", "WKW", 7),
                                   ("CHC", "Unknown", 10),
                                   ("CHC", "Medi School", 10),
                                   ("CHC", "SBS", 10),
                                   ("CHC", "Nanyang Audi", 10),
                                   ("CHC", "SS", 5),
                                   ("CHC", "CEE", 10),
                                   ("CHC", "Earth", 12),
                                   ("CHC", "SCSE", 10),
                                   ("CHC", "MAE", 12),
                                   ("CHC", "NS", 10),
                                   ("CHC", "NS Plaza", 12),
                                   # end of CHC
                                   ("Hive", "SPMS", 1),
                                   ("Hive", "Hall 7", 2),
                                   ("Hive", "EEE1", 2),
                                   ("Hive", "EEE2", 3),
                                   ("Hive", "WKW", 5),
                                   ("Hive", "Unknown", 7),
                                   ("Hive", "Medi School", 7),
                                   ("Hive", "SBS", 7),
                                   ("Hive", "Nanyang Audi", 7),
                                   ("Hive", "SS", 5),
                                   ("Hive", "CEE", 10),
                                   ("Hive", "Earth", 12),
                                   ("Hive", "SCSE", 10),
                                   ("Hive", "MAE", 12),
                                   ("Hive", "NS", 10),
                                   ("Hive", "NS Plaza", 12),
                                   # end of Hive
                                   ("SPMS", "Koufu @ the South Spine", 0),
                                   ("SPMS", "Hall 7", 2),
                                   ("SPMS", "EEE1", 2),
                                   ("SPMS", "EEE2", 3),
                                   ("SPMS", "WKW", 5),
                                   ("SPMS", "Unknown", 7),
                                   ("SPMS", "Medi School", 7),
                                   ("SPMS", "SBS", 7),
                                   ("SPMS", "Nanyang Audi", 7),
                                   ("SPMS", "SS", 5),
                                   ("SPMS", "CEE", 10),
                                   ("SPMS", "Earth", 12),
                                   ("SPMS", "SCSE", 10),
                                   ("SPMS", "MAE", 12),
                                   ("SPMS", "NS", 10),
                                   ("SPMS", "NS Plaza", 12),
                                   # end of SPMS
                                   ("EEE2", "EEE1", 1),
                                   ("EEE2", "WKW", 2),
                                   ("EEE2", "Unknown", 5),
                                   ("EEE2", "Medi School", 5),
                                   ("EEE2", "SBS", 5),
                                   ("EEE2", "Nanyang Audi", 5),
                                   ("EEE2", "SS", 2),
                                   ("EEE2", "CEE", 5),
                                   ("EEE2", "Earth", 7),
                                   ("EEE2", "SCSE", 5),
                                   ("EEE2", "MAE", 7),
                                   ("EEE2", "NS", 5),
                                   ("EEE2", "NS Plaza", 7),
                                   # end of EEE
                                   ("Unknown", "Medi School", 1),
                                   ("Unknown", "SBS", 1),
                                   ("Unknown", "Nanyang Audi", 1),
                                   ("Unknown", "SS", 3),
                                   ("Unknown", "CEE", 3),
                                   ("Unknown", "Earth", 5),
                                   ("Unknown", "SCSE", 3),
                                   ("Unknown", "MAE", 5),
                                   ("Unknown", "NS", 3),
                                   ("Unknown", "NS Plaza", 5),
                                   # end of Unknown
                                   ("Medi School", "SBS", 1),
                                   ("Medi School", "Nanyang Audi", 1),
                                   # end of Medi School
                                   ("SBS", "Nanyang Audi", 1),
                                   # end of SBS
                                   ("SS", "CEE", 5),
                                   ("SS", "Earth", 7),
                                   ("SS", "SCSE", 5),
                                   ("SS", "MAE", 7),
                                   ("SS", "NS", 5),
                                   ("SS", "NS Plaza", 7),
                                   # end of SS
                                   ("CEE", "Earth", 3),
                                   ("CEE", "SCSE", 1),
                                   ("CEE", "MAE", 3),
                                   ("CEE", "NS", 1),
                                   ("CEE", "NS Plaza", 3),
                                   # end of CEE
                                   ("Earth", "SCSE", 3),
                                   ("Earth", "MAE", 1),
                                   ("Earth", "NS", 3),
                                   ("Earth", "NS Plaza", 1),
                                   # end of Earth
                                   ("SCSE", "MAE", 3),
                                   ("SCSE", "NS", 1),
                                   ("SCSE", "NS Plaza", 3),
                                   # end of SCSE
                                   ("MAE", "NS", 3),
                                   ("MAE", "NS Plaza", 1),
                                   # end of MAE
                                   ("NS", "NS Plaza", 3),
                                   # end of NS
                                   ("NS Plaza","North Spine Food Court", 0),
                                   ("NS Plaza","Peach Garden Chinese Restaurant", 0),
                                   ("NS Plaza","Subway", 0)
                                   # end of NS Plaza
                                   ])

# helper function to connect the marks on the graph by weighted edges, whose value represents the walk time between two marks
def add_edges_to_walk(graph):
    graph.add_weighted_edges_from([("Hall 16", "Food Court 16", 0),
                                   ("Hall 16", "Hall 3", 1),
                                   ("Hall 16", "Hall 12", 2),
                                   ("Hall 16", "Hall 13", 3),
                                   ("Hall 16", "Hall 14", 5),
                                   ("Hall 16", "Hall 15", 8),
                                   ("Hall 16", "New Hall", 10),
                                   ("Hall 16", "North Hill Hall", 12),
                                   ("Hall 16", "Hall 10", 15),
                                   ("Hall 16", "Hall 9", 15),
                                   ("Hall 16", "Hall 8", 12),
                                   ("Hall 16", "Hall 11", 12),
                                   ("Hall 16", "ADM", 10),
                                   ("Hall 16", "Hall 2", 12),
                                   ("Hall 16", "Hall 1", 15),
                                   ("Hall 16", "Hall 6", 15),
                                   ("Hall 16", "SRC", 18),
                                   ("Hall 16", "C&P Hall", 20),
                                   ("Hall 16", "Hall 5", 25),
                                   ("Hall 16", "Hall 4", 25),
                                   ("Hall 16", "CHC", 25),
                                   ("Hall 16", "Hive", 20),
                                   ("Hall 16", "SPMS", 20),
                                   ("Hall 16", "Hall 7", 20),
                                   ("Hall 16", "EEE1", 18),
                                   ("Hall 16", "EEE2", 15),
                                   ("Hall 16", "WKW", 20),
                                   ("Hall 16", "Unknown", 15),
                                   ("Hall 16", "Medi School", 15),
                                   ("Hall 16", "SBS", 15),
                                   ("Hall 16", "Nanyang Audi", 15),
                                   ("Hall 16", "SS", 18),
                                   ("Hall 16", "CEE", 12),
                                   ("Hall 16", "Earth", 10),
                                   ("Hall 16", "SCSE", 12),
                                   ("Hall 16", "MAE", 10),
                                   ("Hall 16", "NS", 12),
                                   ("Hall 16", "NS Plaza", 10),
                                   # end of hall 16
                                   ("Hall 3", "Hall 12", 3),
                                   ("Hall 3", "Hall 13", 2),
                                   ("Hall 3", "Hall 14", 4),
                                   ("Hall 3", "Hall 15", 7),
                                   ("Hall 3", "New Hall", 9),
                                   ("Hall 3", "North Hill Hall", 11),
                                   ("Hall 3", "Hall 10", 14),
                                   ("Hall 3", "Hall 9", 14),
                                   ("Hall 3", "Hall 8", 11),
                                   ("Hall 3", "Hall 11", 11),
                                   # end of hall 3
                                   ("Hall 12", "Hall 13", 1),
                                   ("Hall 12", "Hall 14", 4),
                                   ("Hall 12", "Hall 15", 7),
                                   ("Hall 12", "New Hall", 9),
                                   ("Hall 12", "North Hill Hall", 11),
                                   ("Hall 12", "Hall 10", 14),
                                   ("Hall 12", "Hall 9", 14),
                                   ("Hall 12", "Hall 8", 11),
                                   ("Hall 12", "Hall 11", 11),
                                   # end of hall 12
                                   ("Hall 13", "Food Court 13", 0),
                                   ("Hall 13", "Hall 14", 3),
                                   ("Hall 13", "Hall 15", 6),
                                   ("Hall 13", "New Hall", 8),
                                   ("Hall 13", "North Hill Hall", 10),
                                   ("Hall 13", "Hall 10", 13),
                                   ("Hall 13", "Hall 9", 13),
                                   ("Hall 13", "Hall 8", 10),
                                   ("Hall 13", "Hall 11", 10),
                                   # end of Hall 13
                                   ("Hall 14", "Food Court 14", 0),
                                   ("Hall 14", "Hall 15", 1),
                                   ("Hall 14", "New Hall", 5),
                                   ("Hall 14", "North Hill Hall", 8),
                                   ("Hall 14", "Hall 10", 7),
                                   ("Hall 14", "Hall 9", 9),
                                   ("Hall 14", "Hall 8", 9),
                                   ("Hall 14", "Hall 11", 7),
                                   ("Hall 14", "ADM", 10),
                                   ("Hall 14", "Hall 2", 12),
                                   ("Hall 14", "Hall 1", 15),
                                   ("Hall 14", "Hall 6", 15),
                                   ("Hall 14", "SRC", 18),
                                   ("Hall 14", "C&P Hall", 18),
                                   ("Hall 14", "Hall 5", 20),
                                   ("Hall 14", "Hall 4", 22),
                                   # end of Hall 14
                                   ("Hall 15", "New Hall", 3),
                                   ("Hall 15", "North Hill Hall", 5),
                                   # end of Hall 15
                                   ("New Hall", "Foodgle Food Court", 0),
                                   ("New Hall", "North Hill Hall", 5),
                                   ("New Hall", "Hall 10", 5),
                                   ("New Hall", "Hall 9", 6),
                                   ("New Hall", "Hall 8", 6),
                                   ("New Hall", "Hall 11", 5),
                                   ("New Hall", "ADM", 7),
                                   ("New Hall", "Hall 2", 9),
                                   ("New Hall", "Hall 1", 11),
                                   ("New Hall", "Hall 6", 11),
                                   ("New Hall", "SRC", 15),
                                   ("New Hall", "C&P Hall", 18),
                                   ("New Hall", "Hall 5", 20),
                                   ("New Hall", "Hall 4", 22),
                                   ("New Hall", "CHC", 20),
                                   ("New Hall", "Hive", 25),
                                   ("New Hall", "SPMS", 25),
                                   ("New Hall", "Hall 7", 27),
                                   ("New Hall", "EEE1", 25),
                                   ("New Hall", "EEE2", 23),
                                   ("New Hall", "WKW", 25),
                                   ("New Hall", "Unknown", 20),
                                   ("New Hall", "Medi School", 20),
                                   ("New Hall", "SBS", 20),
                                   ("New Hall", "Nanyang Audi", 20),
                                   ("New Hall", "SS", 25),
                                   ("New Hall", "CEE", 18),
                                   ("New Hall", "Earth", 20),
                                   ("New Hall", "SCSE", 18),
                                   ("New Hall", "MAE", 20),
                                   ("New Hall", "NS", 18),
                                   ("New Hall", "NS Plaza", 20),
                                   # end of New Hall
                                   ("North Hill Hall", "North Hill Food Cour", 0),
                                   ("North Hill Hall", "Hall 10", 1),
                                   ("North Hill Hall", "Hall 9", 2),
                                   ("North Hill Hall", "Hall 8", 2),
                                   ("North Hill Hall", "Hall 11", 1),
                                   ("North Hill Hall", "ADM", 5),
                                   ("North Hill Hall", "Hall 2", 7),
                                   ("North Hill Hall", "Hall 1", 9),
                                   ("North Hill Hall", "Hall 6", 9),
                                   ("North Hill Hall", "SRC", 12),
                                   ("North Hill Hall", "C&P Hall", 12),
                                   ("North Hill Hall", "Hall 5", 17),
                                   ("North Hill Hall", "Hall 4", 19),
                                   ("North Hill Hall", "CHC", 20),
                                   ("North Hill Hall", "Hive", 25),
                                   ("North Hill Hall", "SPMS", 25),
                                   ("North Hill Hall", "Hall 7", 27),
                                   ("North Hill Hall", "EEE1", 25),
                                   ("North Hill Hall", "EEE2", 23),
                                   ("North Hill Hall", "WKW", 25),
                                   ("North Hill Hall", "Unknown", 20),
                                   ("North Hill Hall", "Medi School", 20),
                                   ("North Hill Hall", "SBS", 20),
                                   ("North Hill Hall", "Nanyang Audi", 20),
                                   ("North Hill Hall", "SS", 25),
                                   ("North Hill Hall", "CEE", 18),
                                   ("North Hill Hall", "Earth", 20),
                                   ("North Hill Hall", "SCSE", 18),
                                   ("North Hill Hall", "MAE", 20),
                                   ("North Hill Hall", "NS", 18),
                                   ("North Hill Hall", "NS Plaza", 20),
                                   # end of North Hill Hall
                                   ("Hall 9", "Food Court 9", 0),
                                   ("Hall 9", "Hall 8", 1),
                                   ("Hall 9", "Hall 11", 2),
                                   ("Hall 9", "ADM", 5),
                                   ("Hall 9", "Hall 2", 5),
                                   ("Hall 9", "Hall 1", 7),
                                   ("Hall 9", "Hall 6", 7),
                                   ("Hall 9", "SRC", 9),
                                   ("Hall 9", "C&P Hall", 9),
                                   ("Hall 9", "Hall 5", 13),
                                   ("Hall 9", "Hall 4", 15),
                                   ("Hall 9", "CHC", 17),
                                   ("Hall 9", "Hive", 17),
                                   ("Hall 9", "SPMS", 20),
                                   ("Hall 9", "Hall 7", 22),
                                   ("Hall 9", "EEE1", 22),
                                   ("Hall 9", "EEE2", 22),
                                   ("Hall 9", "WKW", 22),
                                   ("Hall 9", "Unknown", 20),
                                   ("Hall 9", "Medi School", 20),
                                   ("Hall 9", "SBS", 20),
                                   ("Hall 9", "Nanyang Audi", 20),
                                   ("Hall 9", "SS", 22),
                                   ("Hall 9", "CEE", 17),
                                   ("Hall 9", "Earth", 17),
                                   ("Hall 9", "SCSE", 17),
                                   ("Hall 9", "MAE", 15),
                                   ("Hall 9", "NS", 17),
                                   ("Hall 9", "NS Plaza", 15),
                                   # end of Hall 9
                                   ("Hall 8", "ADM", 3),
                                   ("Hall 8", "Hall 2", 3),
                                   ("Hall 8", "Hall 1", 5),
                                   ("Hall 8", "Hall 6", 5),
                                   ("Hall 8", "SRC", 7),
                                   ("Hall 8", "C&P Hall", 7),
                                   ("Hall 8", "Hall 5", 13),
                                   ("Hall 8", "Hall 4", 15),
                                   ("Hall 8", "CHC", 17),
                                   ("Hall 8", "Hive", 17),
                                   ("Hall 8", "SPMS", 20),
                                   ("Hall 8", "Hall 7", 22),
                                   ("Hall 8", "EEE1", 22),
                                   ("Hall 8", "EEE2", 22),
                                   ("Hall 8", "WKW", 22),
                                   ("Hall 8", "Unknown", 20),
                                   ("Hall 8", "Medi School", 20),
                                   ("Hall 8", "SBS", 20),
                                   ("Hall 8", "Nanyang Audi", 20),
                                   ("Hall 8", "SS", 22),
                                   ("Hall 8", "CEE", 17),
                                   ("Hall 8", "Earth", 17),
                                   ("Hall 8", "SCSE", 17),
                                   ("Hall 8", "MAE", 15),
                                   ("Hall 8", "NS", 17),
                                   ("Hall 8", "NS Plaza", 15),
                                   # end of Hall 8
                                   ("ADM", "Hall 2", 2),
                                   ("ADM", "Hall 1", 3),
                                   ("ADM", "Hall 6", 3),
                                   ("ADM", "SRC", 5),
                                   ("ADM", "C&P Hall", 7),
                                   ("ADM", "Hall 5", 12),
                                   ("ADM", "Hall 4", 12),
                                   ("ADM", "CHC", 15),
                                   ("ADM", "Hive", 12),
                                   ("ADM", "SPMS", 12),
                                   ("ADM", "Hall 7", 15),
                                   ("ADM", "EEE1", 12),
                                   ("ADM", "EEE2", 13),
                                   ("ADM", "WKW", 15),
                                   ("ADM", "Unknown", 10),
                                   ("ADM", "Medi School", 10),
                                   ("ADM", "SBS", 10),
                                   ("ADM", "Nanyang Audi", 10),
                                   ("ADM", "SS", 15),
                                   ("ADM", "CEE", 10),
                                   ("ADM", "Earth", 8),
                                   ("ADM", "SCSE", 10),
                                   ("ADM", "MAE", 8),
                                   ("ADM", "NS", 10),
                                   ("ADM", "NS Plaza", 8),
                                   # end of ADM
                                   ("Hall 2", "Food Court 2", 0),
                                   ("Hall 2", "Hall 1", 2),
                                   ("Hall 2", "Hall 6", 2),
                                   ("Hall 2", "SRC", 3),
                                   ("Hall 2", "C&P Hall", 5),
                                   ("Hall 2", "Hall 5", 8),
                                   ("Hall 2", "Hall 4", 10),
                                   ("Hall 2", "CHC", 10),
                                   ("Hall 2", "Hive", 10),
                                   ("Hall 2", "SPMS", 15),
                                   ("Hall 2", "Hall 7", 17),
                                   ("Hall 2", "EEE1", 12),
                                   ("Hall 2", "EEE2", 13),
                                   ("Hall 2", "WKW", 15),
                                   ("Hall 2", "Unknown", 10),
                                   ("Hall 2", "Medi School", 10),
                                   ("Hall 2", "SBS", 10),
                                   ("Hall 2", "Nanyang Audi", 5),
                                   ("Hall 2", "SS", 5),
                                   ("Hall 2", "CEE", 5),
                                   ("Hall 2", "Earth", 8),
                                   ("Hall 2", "SCSE", 5),
                                   ("Hall 2", "MAE", 8),
                                   ("Hall 2", "NS", 5),
                                   ("Hall 2", "NS Plaza", 8),
                                   # end of hall 2
                                   ("Hall 1", "Food Court 1", 0),
                                   ("Hall 1", "Hall 6", 1),
                                   ("Hall 1", "SRC", 3),
                                   ("Hall 1", "C&P Hall", 1),
                                   ("Hall 1", "Hall 5", 3),
                                   ("Hall 1", "Hall 4", 8),
                                   ("Hall 1", "CHC", 10),
                                   ("Hall 1", "Hive", 10),
                                   ("Hall 1", "SPMS", 12),
                                   ("Hall 1", "Hall 7", 15),
                                   ("Hall 1", "EEE1", 12),
                                   ("Hall 1", "EEE2", 13),
                                   ("Hall 1", "WKW", 15),
                                   ("Hall 1", "Unknown", 10),
                                   ("Hall 1", "Medi School", 10),
                                   ("Hall 1", "SBS", 10),
                                   ("Hall 1", "Nanyang Audi", 10),
                                   ("Hall 1", "SS", 15),
                                   ("Hall 1", "CEE", 15),
                                   ("Hall 1", "Earth", 18),
                                   ("Hall 1", "SCSE", 15),
                                   ("Hall 1", "MAE", 18),
                                   ("Hall 1", "NS", 15),
                                   ("Hall 1", "NS Plaza", 18),
                                   # end of Hall 1
                                   ("Hall 6", "SRC", 1),
                                   ("Hall 6", "C&P Hall", 1),
                                   # end of Hall 6
                                   ("C&P Hall", "Pioneer Food Court", 0),
                                   # end of C&P Hall
                                   ("Hall 5", "Hall 4", 1),
                                   ("Hall 5", "CHC", 3),
                                   ("Hall 5", "Hive", 5),
                                   ("Hall 5", "SPMS", 5),
                                   ("Hall 5", "Hall 7", 7),
                                   ("Hall 5", "EEE1", 5),
                                   ("Hall 5", "EEE2", 5),
                                   ("Hall 5", "WKW", 7),
                                   ("Hall 5", "Unknown", 10),
                                   ("Hall 5", "Medi School", 10),
                                   ("Hall 5", "SBS", 10),
                                   ("Hall 5", "Nanyang Audi", 10),
                                   ("Hall 5", "SS", 15),
                                   ("Hall 5", "CEE", 10),
                                   ("Hall 5", "Earth", 8),
                                   ("Hall 5", "SCSE", 10),
                                   ("Hall 5", "MAE", 8),
                                   ("Hall 5", "NS", 10),
                                   ("Hall 5", "NS Plaza", 8),
                                   # end of Hall 5
                                   ("Hall 4", "CHC", 3),
                                   ("Hall 4", "Hive", 5),
                                   ("Hall 4", "SPMS", 5),
                                   ("Hall 4", "Hall 7", 7),
                                   ("Hall 4", "EEE1", 5),
                                   ("Hall 4", "EEE2", 5),
                                   # end of Hall 4
                                   ("CHC", "Hive", 1),
                                   ("CHC", "SPMS", 2),
                                   ("CHC", "Hall 7", 3),
                                   ("CHC", "EEE1", 3),
                                   ("CHC", "EEE2", 3),
                                   ("CHC", "WKW", 7),
                                   ("CHC", "Unknown", 10),
                                   ("CHC", "Medi School", 10),
                                   ("CHC", "SBS", 10),
                                   ("CHC", "Nanyang Audi", 10),
                                   ("CHC", "SS", 5),
                                   ("CHC", "CEE", 10),
                                   ("CHC", "Earth", 12),
                                   ("CHC", "SCSE", 10),
                                   ("CHC", "MAE", 12),
                                   ("CHC", "NS", 10),
                                   ("CHC", "NS Plaza", 12),
                                   # end of CHC
                                   ("Hive", "SPMS", 1),
                                   ("Hive", "Hall 7", 2),
                                   ("Hive", "EEE1", 2),
                                   ("Hive", "EEE2", 3),
                                   ("Hive", "WKW", 5),
                                   ("Hive", "Unknown", 7),
                                   ("Hive", "Medi School", 7),
                                   ("Hive", "SBS", 7),
                                   ("Hive", "Nanyang Audi", 7),
                                   ("Hive", "SS", 5),
                                   ("Hive", "CEE", 10),
                                   ("Hive", "Earth", 12),
                                   ("Hive", "SCSE", 10),
                                   ("Hive", "MAE", 12),
                                   ("Hive", "NS", 10),
                                   ("Hive", "NS Plaza", 12),
                                   # end of Hive
                                   ("SPMS", "Koufu @ the South Spine", 0),
                                   ("SPMS", "Hall 7", 2),
                                   ("SPMS", "EEE1", 2),
                                   ("SPMS", "EEE2", 3),
                                   ("SPMS", "WKW", 5),
                                   ("SPMS", "Unknown", 7),
                                   ("SPMS", "Medi School", 7),
                                   ("SPMS", "SBS", 7),
                                   ("SPMS", "Nanyang Audi", 7),
                                   ("SPMS", "SS", 5),
                                   ("SPMS", "CEE", 10),
                                   ("SPMS", "Earth", 12),
                                   ("SPMS", "SCSE", 10),
                                   ("SPMS", "MAE", 12),
                                   ("SPMS", "NS", 10),
                                   ("SPMS", "NS Plaza", 12),
                                   # end of SPMS
                                   ("EEE2", "EEE1", 1),
                                   ("EEE2", "WKW", 2),
                                   ("EEE2", "Unknown", 5),
                                   ("EEE2", "Medi School", 5),
                                   ("EEE2", "SBS", 5),
                                   ("EEE2", "Nanyang Audi", 5),
                                   ("EEE2", "SS", 2),
                                   ("EEE2", "CEE", 5),
                                   ("EEE2", "Earth", 7),
                                   ("EEE2", "SCSE", 5),
                                   ("EEE2", "MAE", 7),
                                   ("EEE2", "NS", 5),
                                   ("EEE2", "NS Plaza", 7),
                                   # end of EEE
                                   ("Unknown", "Medi School", 1),
                                   ("Unknown", "SBS", 1),
                                   ("Unknown", "Nanyang Audi", 1),
                                   ("Unknown", "SS", 3),
                                   ("Unknown", "CEE", 3),
                                   ("Unknown", "Earth", 5),
                                   ("Unknown", "SCSE", 3),
                                   ("Unknown", "MAE", 5),
                                   ("Unknown", "NS", 3),
                                   ("Unknown", "NS Plaza", 5),
                                   # end of Unknown
                                   ("Medi School", "SBS", 1),
                                   ("Medi School", "Nanyang Audi", 1),
                                   # end of Medi School
                                   ("SBS", "Nanyang Audi", 1),
                                   # end of SBS
                                   ("SS", "CEE", 5),
                                   ("SS", "Earth", 7),
                                   ("SS", "SCSE", 5),
                                   ("SS", "MAE", 7),
                                   ("SS", "NS", 5),
                                   ("SS", "NS Plaza", 7),
                                   # end of SS
                                   ("CEE", "Earth", 3),
                                   ("CEE", "SCSE", 1),
                                   ("CEE", "MAE", 3),
                                   ("CEE", "NS", 1),
                                   ("CEE", "NS Plaza", 3),
                                   # end of CEE
                                   ("Earth", "SCSE", 3),
                                   ("Earth", "MAE", 1),
                                   ("Earth", "NS", 3),
                                   ("Earth", "NS Plaza", 1),
                                   # end of Earth
                                   ("SCSE", "MAE", 3),
                                   ("SCSE", "NS", 1),
                                   ("SCSE", "NS Plaza", 3),
                                   # end of SCSE
                                   ("MAE", "NS", 3),
                                   ("MAE", "NS Plaza", 1),
                                   # end of MAE
                                   ("NS", "NS Plaza", 3),
                                   # end of NS
                                   ("NS Plaza","North Spine Food Court", 0),
                                   ("NS Plaza","Peach Garden Chinese Restaurant", 0),
                                   ("NS Plaza","Subway", 0)
                                   # end of NS Plaza
                                   ])

# helper function to generate walk.graphml and shuttle.graphml
# use the marks as the points and call the two add_edges functions to add edges to the graph
def generate_graphml():
    graph = nx.Graph()

    graph.add_nodes_from([i for i in canteen])
    graph.add_nodes_from([i for i in mark])

    add_edges_to_shuttle(graph)
    nx.write_graphml(graph, "dataset/shuttle.graphml")

    graph = nx.Graph()

    graph.add_nodes_from([i for i in canteen])
    graph.add_nodes_from([i for i in mark])

    add_edges_to_walk(graph)
    nx.write_graphml(graph, "dataset/walk.graphml")
